on:
  push:
    branches:
      - "main"
      - "humble"
  workflow_dispatch:

jobs:
  deploy-main-image:
    name: Build and deploy main docker image
    runs-on: ubuntu-latest
    env:
      PLATFORM: linux/amd64
      MAIN_IMAGE: ghcr.io/${{ github.repository_owner }}/firo_robot

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract branch name
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            SAFE_BRANCH=$(echo "${{ github.ref_name }}" | tr '/' '-')
            echo "BRANCH=$SAFE_BRANCH" >>${GITHUB_ENV}
          else
            SAFE_BRANCH=$(git rev-parse --abbrev-ref HEAD | tr '/' '-')
            echo "BRANCH=$SAFE_BRANCH" >>${GITHUB_ENV}
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install -D semantic-release @semantic-release/exec conventional-changelog-conventionalcommits

      - name: Tag version
        id: semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=$(npx semantic-release -t "${{env.BRANCH}}-\${version}" 2>&1 | grep -oP '(?<=Published release )\d+\.\d+\.\d+' || echo "")
          if [ -z "$VERSION" ]; then
            VERSION="latest"
          fi
          echo "next_version=$VERSION" >> $GITHUB_ENV

      - name: Lowercase image name
        if: ${{ env.next_version || github.event_name == 'workflow_dispatch' }}
        run: |
          echo "MAIN_IMAGE=${MAIN_IMAGE,,}" >>${GITHUB_ENV}

      - name: Set up QEMU
        if: ${{ env.next_version || github.event_name == 'workflow_dispatch' }}
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: ${{ env.next_version || github.event_name == 'workflow_dispatch' }}
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        if: ${{ env.next_version || github.event_name == 'workflow_dispatch' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push image
        if: ${{ env.next_version || github.event_name == 'workflow_dispatch' }}
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile
          push: true
          provenance: false # Remove in the future. Currently ghcr does not parse it correctly
          tags: |
            ${{ env.MAIN_IMAGE }}:${{env.BRANCH}}-${{ env.next_version }}
            ${{ env.MAIN_IMAGE }}:${{env.BRANCH}}
          platforms: ${{ env.PLATFORM }}
          cache-from: ${{ env.MAIN_IMAGE }}:${{env.BRANCH}}
          build-args: BUILDKIT_INLINE_CACHE=1
