on:
  push:
    branches:
      - "main"
      - "humble"
  workflow_dispatch:
    inputs:
      force_build:
        description: "Force build and push even if no new version is created"
        required: false
        default: "false"
      manual_version:
        description: "Manually specify the version (optional)"
        required: false
        default: ""

jobs:
  deploy-main-image:
    name: Build and deploy main docker image
    runs-on: ubuntu-latest
    env:
      PLATFORM: linux/amd64
      MAIN_IMAGE: ghcr.io/${{ github.repository_owner }}/firo_robot

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract branch name
        run: echo "BRANCH=${GITHUB_REF##*/}" >>${GITHUB_ENV}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install -D semantic-release @semantic-release/exec conventional-changelog-conventionalcommits

      - name: Tag version
        id: semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ -n "${{ inputs.manual_version }}" ]]; then
            echo "next_version=${{ inputs.manual_version }}" >> $GITHUB_ENV
          else
            VERSION=$(npx semantic-release -t "${{env.BRANCH}}-\${version}")
            if [[ $? -eq 0 ]]; then
              echo "next_version=$VERSION" >> $GITHUB_ENV
            fi
          fi

      - name: Force build if enabled
        run: echo "FORCE_BUILD=${{ inputs.force_build }}" >> $GITHUB_ENV

      - name: lowercase image name
        if: env.next_version || env.FORCE_BUILD == 'true'
        run: |
          echo "MAIN_IMAGE=${MAIN_IMAGE,,}" >>${GITHUB_ENV}

      - name: Set up QEMU
        if: env.next_version || env.FORCE_BUILD == 'true'
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: env.next_version || env.FORCE_BUILD == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        if: env.next_version || env.FORCE_BUILD == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push image
        if: env.next_version || env.FORCE_BUILD == 'true'
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile
          push: true
          provenance: false
          tags: |
            ${{ env.MAIN_IMAGE }}:${{env.BRANCH}}-${{env.next_version}}
            ${{ env.MAIN_IMAGE }}:${{env.BRANCH}}
          platforms: ${{ env.PLATFORM }}
          cache-from: ${{ env.MAIN_IMAGE }}:${{env.BRANCH}}
          build-args: BUILDKIT_INLINE_CACHE=1
